[package]
name = "rush"
version = "0.1.0"
authors = ["ashpil <ashpil@pm.me>", "focus172 <evan.stokdyk@gmail.com"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libshards = { path = "../../crates/shardstypes/" }
os_pipe = "1.1"
nix = { version = "0.27", features = ["user"] }
