[package]
name = "rushi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shards-types = { path = "../shards-types" }
syn = { version = "2", features = ["full", "extra-traits"] }
libc = "0.2"
