[package]
name = "shards-sys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log.workspace = true
resu.workspace = true
libshards-core = { path = "../libshards-core/" }
